---
- name: "{{ tenant.name | upper }} | set tenant variables" 
  set_fact:
    asset_dest: "{{ catalog_web_assets_home }}/{{ tenant.name | lower }}"
 
- debug:
    msg: " {{ item }}" 
    verbosity: 1
  with_items:
    - "asset destination dir: {{ asset_dest }}"

- include_tasks:
    file: asset.yml
  loop: "{{ tenant.catalog }}"  
  loop_control:
    loop_var: catalog    
